#"The network line must be present here"

# https://docs.docker.com/engine/network/

#The Dockerfiles must be called here

#But the containers mustn't be started with a command running an infinite loop (Forbidden stuff: tail -f, bash, sleep infinity, while true)

#About PID 1: https://daveiscoding.hashnode.dev/why-do-you-need-an-init-process-inside-your-docker-container-pid-1

#https://www.codecademy.com/article/mastering-docker-compose

#version: '2' #The version of docker compose we are using - might neeed to change this

services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:skorbai
    ports:
      - 3306
    env_file:
      - ".env"
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception_network
    restart: always
      

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:skorbai
    ports:
      - "443:443"
    env_file:
      - ".env"
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:skorbai
    depends_on:
      - mariadb
      - nginx
    env_file:
      - ".env"
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception_network
    restart: on-failure

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      device: /home/skorbai/data/database
      o: bind
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/skorbai/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge
