#"The network line must be present here"

# https://docs.docker.com/engine/network/

#The Dockerfiles must be called here

#But the containers mustn't be started with a command running an infinite loop (Forbidden stuff: tail -f, bash, sleep infinity, while true)

#About PID 1: https://daveiscoding.hashnode.dev/why-do-you-need-an-init-process-inside-your-docker-container-pid-1

#https://www.codecademy.com/article/mastering-docker-compose

version: '2' #The version of docker compose we are using - might neeed to change this

services:

  db:
    container_name: mariadb_container
    build:
      context: srcs/requirements/mariadb
      dockerfile: srcs/requirements/mariadb/Dockerfile
    image: mariadb_image
    env_file:
      - "srcs/.env"
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception_network
    restart: always
      

  server:
    container_name: nginx_container
    build:
      context: srcs/requirements/nginx
      dockerfile: srcs/requirements/nginx/Dockerfile
    image: nginx_image
    env_file:
      - "srcs/.env"
    networks:
      - inception_network
    restart: on-failure

  web:
    container_name: wordpress_container
    build:
      context: srcs/requirements/wordpress
      dockerfile: srcs/requirements/wordpress/Dockerfile
    image: wordpress_image
    depends_on:
      - db
      - nginx
    env_file:
      - "srcs/.env"
    volumes:
      - web_volume:/var/www/html
    networks:
      - inception_network
    restart: on-failure

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/skorbai/data/database
      o: bind
  web_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/skorbai/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge